name: Get latest release version
on:
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/qpincon/test-fetch-release/releases/latest | \
          jq -r ".tag_name" > release-versions/test-latest.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Perform simplification
        if: steps.git-check.outputs.modified == 'true'
        id: simplify
        uses: actions/get_world_and_simplify_action
      - name: Commit latest release version and new generated topojson
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'qpincon'
          git config --global user.email 'qpincon@users.noreply.github.com'
          git commit -am "New release of test repo: new simplified topojson created"
          git push
