name: Get latest release version
on:
  schedule:
  -  cron:  '*/5 * * * *'
jobs:
  get-release-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
